#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration
i=1
while [ $i -le 9 ]; do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
	echo "Best School"
    fi
    ((i++))
done
